{% set version = "0.3.6" %}

package:
  name: komplexity
  version: {{ version }}

source:
  url: https://github.com/eclarke/komplexity/releases/download/v{{ version }}/kz-v{{ version }}-linux.zip
  fn: kz-v{{ version }}-linux.zip
  sha256: 429899a7773fe7ab695beb521dfb3197cbbe1ccb6213dae717bf70bf9ec5794e

build:
  number: 1
  string: musl

test:
  commands:
    - kz -h

about:
  home: https://github.com/eclarke/komplexity

